### ISSUE TITLE
Cannot be build with FFmpeg 7.0

### ISSUE THREAD

**Issue by data-man** [xiaoyifang/goldendict-ng#1523]
```log
/home/dataman/Projects/goldendict-ng_staged/src/ffmpegaudio.cc:184:27: error: no member named 'channels' in 'AVCodecContext'
  184 |            codecContext_->channels,
      |            ~~~~~~~~~~~~~  ^
/home/dataman/Projects/goldendict-ng_staged/src/ffmpegaudio.cc:188:32: error: no member named 'channel_layout' in 'AVCodecContext'
  188 |   auto layout = codecContext_->channel_layout;
      |                 ~~~~~~~~~~~~~  ^
/home/dataman/Projects/goldendict-ng_staged/src/ffmpegaudio.cc:190:83: error: no member named 'channels' in 'AVCodecContext'
  190 |     layout                        = av_get_default_channel_layout( codecContext_->channels );
      |                                                                    ~~~~~~~~~~~~~  ^
/home/dataman/Projects/goldendict-ng_staged/src/ffmpegaudio.cc:191:20: error: no member named 'channel_layout' in 'AVCodecContext'
  191 |     codecContext_->channel_layout = layout;
      |     ~~~~~~~~~~~~~  ^
/home/dataman/Projects/goldendict-ng_staged/src/ffmpegaudio.cc:248:5: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
  248 |     avcodec_close( codecContext_ );
      |     ^
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
 2386 | attribute_deprecated
      | ^
/usr/include/x86_64-linux-gnu/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
/home/dataman/goldendict-ng_staged/src/ffmpegaudio.cc:272:54: error: no member named 'channels' in 'AVCodecContext'
  272 |   audioOutput->setAudioFormat( 44100, codecContext_->channels );
      |                                       ~~~~~~~~~~~~~  ^
/home/dataman/goldendict-ng_staged/src/ffmpegaudio.cc:332:38: error: no member named 'channels' in 'AVCodecContext'
  332 |   auto dst_channels = codecContext_->channels;
      |                       ~~~~~~~~~~~~~  ^
```

**Comment by shenlebantongying** [comment]
We don't actually need the FFmpeg backend anymore. Newer Qt6's multimedia has FFmpeg backend, the supported formats are the same. 

Maybe this is the time to delete the FFmpeg backend 😅

Qt's doc says other backends are somewhat deprecated https://doc.qt.io/qt-6/qtmultimedia-index.html#ffmpeg-as-the-default-backend

On Linux distros, this can ensure the backend.
```
export QT_MEDIA_BACKEND=ffmpeg
```

**Comment by data-man** [comment]
> export QT_MEDIA_BACKEND=ffmpeg

This will affect all Qt applications, that is not desirable.
Maybe change `WITH_FFMPEG_PLAYER` option to `OFF` by default?

**Comment by Initsnow** [comment]
On Windows 11, I can't play sounds using Qt Multimedia.  It didn't work fine until I used ffplay

**Comment by Initsnow** [comment]
> On Windows 11, I can't play sounds using Qt Multimedia. It didn't fine work until I used ffplay

I know what's going on. I installed the N version of Windows before, so it didn't come with the audio component that comes with the system.

**Comment by xiaoyifang** [comment]
> Maybe change `WITH_FFMPEG_PLAYER` option to `OFF` by default?

@shenlebantongying on Linux Platform,what do you think?

**Comment by shenlebantongying** [comment]
I think the 6.8 is LTS this September.

How about we cut another release in September? It will be the last version that contains code for Qt5, qmake and FFmpeg?

After that, we delete all of them.

https://wiki.qt.io/Qt_6.8_Release

**Comment by xiaoyifang** [comment]
I think ,these two tasks can be in parallel.
1, WITH_FFMPEG_PLAYER =OFF
2, remove Qt5 code later.

**Comment by shenlebantongying** [comment]
(As you can see, there is a bug right in our face, as reported by @Initsnow . The Qt multimedia, for some reason, defaults to Windows's media API 😅. )

**Comment by xiaoyifang** [comment]
I guess the windeployqt has not deployed the ffmpeg dlls with the application.

**Comment by xiaoyifang** [comment]
> (As you can see, there is a bug right in our face, as reported by @Initsnow . The Qt multimedia, for some reason, defaults to Windows's media API 😅. We can wait for a few mouths.)

The windows release has built with ffmpeg disabled.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/2faa9a06-5f3c-4c8a-b3ef-ecb70832f937)

**Comment by data-man** [comment]
> After that, we delete all of them.

Note, that some Linux distros don't have latest Qt.
E. g. Debian and Devuan (I use it :smile:) has 6.4.2.
